Repository munich-quantum-toolkit/bench, pull requests merged in 2023-02, with the labels that each got.

#170 :dependabot: Dependency management
  pyproject.toml
Labels: enhancement, dependencies

#171 🐛 Quick-fix for uni-directional routing with TKET
  mqt/bench/tests/test_all.py
  mqt/bench/utils/tket_helper.py
Labels: bug

#173 🔧 Configure GITHUB_TOKEN API Authorization
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  mqt/benchviewer/src/backend.py
Labels: enhancement

#174 ✨🚨 Introduce Ruff as Pre-Commit Check
  .flake8
  .pre-commit-config.yaml
  mqt/bench/benchmark_generator.py
  mqt/bench/benchmarks/dj.py
  mqt/bench/benchmarks/grover.py
  mqt/bench/benchmarks/qiskit_application_finance/portfolioqaoa.py
  mqt/bench/benchmarks/qiskit_application_finance/portfoliovqe.py
  mqt/bench/benchmarks/qiskit_application_finance/pricingcall.py
  mqt/bench/benchmarks/qiskit_application_finance/pricingput.py
  mqt/bench/benchmarks/qiskit_application_ml/qgan.py
  mqt/bench/benchmarks/qiskit_application_nature/groundstate.py
  mqt/bench/benchmarks/qiskit_application_optimization/routing.py
  mqt/bench/benchmarks/qwalk.py
  mqt/bench/tests/test_all.py
  mqt/bench/utils/qiskit_helper.py
  mqt/bench/utils/tket_helper.py
  mqt/bench/utils/utils.py
  mqt/benchviewer/main.py
  mqt/benchviewer/src/backend.py
  mqt/benchviewer/src/tests/test_backend.py
  pyproject.toml
Labels: enhancement

#179 Fix Typos
  src/mqt/benchviewer/templates/description.html
  src/mqt/benchviewer/templates/index.html
Labels: documentation

#178 Evaluation Routine Implementation
  .pre-commit-config.yaml
  src/mqt/bench/evaluation/__init__.py
  src/mqt/bench/evaluation/evaluation.py
  src/mqt/bench/evaluation/evaluation_visualization.ipynb
  src/mqt/bench/evaluation/results/pie.pdf
  src/mqt/bench/evaluation/results/qubit_dist.pdf
  src/mqt/bench/evaluation/results/violins.pdf
  src/mqt/bench/utils.py
  tests/test_bench.py
Labels: enhancement

#187 🔥 removed old shield from Readme
  README.md
Labels: bug, continuous integration
