Repository munich-quantum-toolkit/bench, pull requests merged in 2024-05, with the labels that each got.

#324 💡 Add PennyLane reference
  README.md
  docs/index.rst
  src/mqt/bench/viewer/templates/index.html
Labels: documentation, enhancement

#327 📝 Fix MQT Logo in README
  README.md
  docs/_static/erc_dark.svg
  docs/_static/erc_light.svg
  docs/_static/logo-bavaria.svg
  docs/_static/logo-mqv.svg
  docs/_static/tum_dark.svg
  docs/_static/tum_light.svg
  docs/_templates/page.html
Labels: documentation

#328 💡 fixed minor readme issues
  CITATION.bib
  LICENSE
  MANIFEST.in
  README.md
Labels: documentation, enhancement

#331 📝 Add docstring check to ruff and fix respective errors
  pyproject.toml
  src/mqt/bench/__init__.py
  src/mqt/bench/benchmark_generator.py
  src/mqt/bench/benchmarks/__init__.py
  src/mqt/bench/benchmarks/ae.py
  src/mqt/bench/benchmarks/dj.py
  src/mqt/bench/benchmarks/ghz.py
  src/mqt/bench/benchmarks/graphstate.py
  src/mqt/bench/benchmarks/grover.py
  src/mqt/bench/benchmarks/qaoa.py
  src/mqt/bench/benchmarks/qft.py
  src/mqt/bench/benchmarks/qftentangled.py
  src/mqt/bench/benchmarks/qiskit_application_finance/portfolioqaoa.py
  src/mqt/bench/benchmarks/qiskit_application_finance/portfoliovqe.py
  src/mqt/bench/benchmarks/qiskit_application_finance/pricingcall.py
  src/mqt/bench/benchmarks/qiskit_application_finance/pricingput.py
  src/mqt/bench/benchmarks/qiskit_application_ml/qnn.py
  src/mqt/bench/benchmarks/qiskit_application_nature/groundstate.py
  src/mqt/bench/benchmarks/qiskit_application_optimization/routing.py
  src/mqt/bench/benchmarks/qiskit_application_optimization/tsp.py
  src/mqt/bench/benchmarks/qpeexact.py
  src/mqt/bench/benchmarks/qpeinexact.py
  src/mqt/bench/benchmarks/qwalk.py
  src/mqt/bench/benchmarks/random.py
  src/mqt/bench/benchmarks/realamprandom.py
  src/mqt/bench/benchmarks/shor.py
  src/mqt/bench/benchmarks/su2random.py
  src/mqt/bench/benchmarks/twolocalrandom.py
  src/mqt/bench/benchmarks/vqe.py
  src/mqt/bench/benchmarks/wstate.py
  src/mqt/bench/cli.py
  src/mqt/bench/devices/__init__.py
  src/mqt/bench/devices/calibration.py
  src/mqt/bench/devices/device.py
  src/mqt/bench/devices/ibm.py
  src/mqt/bench/devices/ionq.py
  src/mqt/bench/devices/oqc.py
  src/mqt/bench/devices/provider.py
  src/mqt/bench/devices/quantinuum.py
  src/mqt/bench/devices/rigetti.py
  src/mqt/bench/evaluation/__init__.py
  src/mqt/bench/evaluation/evaluation.py
  src/mqt/bench/qiskit_helper.py
  src/mqt/bench/tket_helper.py
  src/mqt/bench/utils.py
  src/mqt/bench/viewer/__init__.py
  src/mqt/bench/viewer/backend.py
  src/mqt/bench/viewer/main.py
  tests/devices/test_devices.py
  tests/devices/test_ibm_device_support.py
  tests/devices/test_ionq_device_support.py
  tests/devices/test_oqc_device_support.py
  tests/devices/test_quantinuum_device_support.py
  tests/devices/test_rigetti_device_support.py
  tests/test_bench.py
  tests/test_benchviewer.py
  tests/test_cli.py
  tests/test_pregenerated_zip.py
Labels: documentation, enhancement

#337 ⬆️ update black version in blacken-docs
  .pre-commit-config.yaml
Labels: dependencies, continuous integration
