Repository munich-quantum-toolkit/bench, pull requests merged in 2024-09, with the labels that each got.

#374 reverted unwanted downgrade of typos
  .pre-commit-config.yaml
Labels: continuous integration

#382 Corrected the readme ghz-example
  README.md
Labels: documentation, mqt.bench

#377 ⚗️ update mqt-workflows version
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  noxfile.py
Labels: github_actions, python, continuous integration

#383 ⚡🚨 make `qiskit_optimization` import lazy
  src/mqt/bench/utils.py
Labels: python, usability, mqt.bench

#392 👷 adjusted to mqt workflow update
  docs/conf.py
  noxfile.py
  pyproject.toml
  uv.lock
Labels: continuous integration
