Repository munich-quantum-toolkit/bench, pull requests merged in 2024-04, with the labels that each got.

#315 Improve ruff config
  .pre-commit-config.yaml
  docs/Abstraction_levels.rst
  docs/Parameter.rst
  noxfile.py
  pyproject.toml
  src/mqt/bench/__init__.py
  src/mqt/bench/benchmark_generator.py
  src/mqt/bench/benchmarks/__init__.py
  src/mqt/bench/benchmarks/ae.py
  src/mqt/bench/benchmarks/dj.py
  src/mqt/bench/benchmarks/ghz.py
  src/mqt/bench/benchmarks/graphstate.py
  src/mqt/bench/benchmarks/grover.py
  src/mqt/bench/benchmarks/qaoa.py
  src/mqt/bench/benchmarks/qft.py
  src/mqt/bench/benchmarks/qftentangled.py
  src/mqt/bench/benchmarks/qiskit_application_finance/portfolioqaoa.py
  src/mqt/bench/benchmarks/qiskit_application_finance/portfoliovqe.py
  src/mqt/bench/benchmarks/qiskit_application_finance/pricingcall.py
  src/mqt/bench/benchmarks/qiskit_application_finance/pricingput.py
  src/mqt/bench/benchmarks/qiskit_application_ml/qnn.py
  src/mqt/bench/benchmarks/qiskit_application_nature/groundstate.py
  src/mqt/bench/benchmarks/qiskit_application_optimization/routing.py
  src/mqt/bench/benchmarks/qiskit_application_optimization/tsp.py
  src/mqt/bench/benchmarks/qpeexact.py
  src/mqt/bench/benchmarks/qpeinexact.py
  src/mqt/bench/benchmarks/qwalk.py
  src/mqt/bench/benchmarks/random.py
  src/mqt/bench/benchmarks/realamprandom.py
  src/mqt/bench/benchmarks/shor.py
  src/mqt/bench/benchmarks/su2random.py
  src/mqt/bench/benchmarks/twolocalrandom.py
  src/mqt/bench/benchmarks/vqe.py
  src/mqt/bench/benchmarks/wstate.py
  src/mqt/bench/devices/__init__.py
  src/mqt/bench/devices/calibration.py
  src/mqt/bench/devices/device.py
  src/mqt/bench/devices/ibm.py
  src/mqt/bench/devices/ionq.py
  src/mqt/bench/devices/oqc.py
  src/mqt/bench/devices/provider.py
  src/mqt/bench/devices/quantinuum.py
  src/mqt/bench/devices/rigetti.py
  src/mqt/bench/evaluation/__init__.py
  src/mqt/bench/qiskit_helper.py
  src/mqt/bench/tket_helper.py
  src/mqt/bench/utils.py
  src/mqt/benchviewer/__init__.py
  src/mqt/benchviewer/backend.py
  src/mqt/benchviewer/main.py
  src/mqt/benchviewer/templates/index.html
  tests/devices/test_devices.py
  tests/devices/test_ibm_device_support.py
  tests/devices/test_ionq_device_support.py
  tests/devices/test_oqc_device_support.py
  tests/devices/test_quantinuum_device_support.py
  tests/devices/test_rigetti_device_support.py
  tests/test_bench.py
Labels: enhancement

#319 Remove setup.py reference
  pyproject.toml
Labels: enhancement

#321 Add basic CLI around get_benchmark()
  pyproject.toml
  src/mqt/bench/benchmark_generator.py
  src/mqt/bench/cli.py
  tests/test_cli.py
Labels: python, usability, feature

#322 ✨ improve CI/CD and package itself
  .github/codecov.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/mypy.yml
  .github/workflows/release-drafter.yml
  .github/workflows/test_pregenerated_zip.yml
  .pre-commit-config.yaml
  README.md
  noxfile.py
  pyproject.toml
  src/mqt/bench/benchmark_generator.py
  src/mqt/bench/benchmarks/qiskit_application_nature/groundstate.py
  src/mqt/bench/utils.py
  src/mqt/bench/viewer/__init__.py
  src/mqt/bench/viewer/backend.py
  src/mqt/bench/viewer/main.py
  src/mqt/bench/viewer/static/favicon.ico
  src/mqt/bench/viewer/static/files/MQTBench_all.zip
  src/mqt/bench/viewer/static/files/qasm_output/.gitignore
  src/mqt/bench/viewer/static/mqt_dark.png
  src/mqt/bench/viewer/static/tum_logo.svg
  src/mqt/bench/viewer/templates/benchmark_description.html
  src/mqt/bench/viewer/templates/description.html
  src/mqt/bench/viewer/templates/index.html
  src/mqt/bench/viewer/templates/legal.html
  src/mqt/benchviewer/__init__.py
  src/mqt/benchviewer/py.typed
  tests/test_bench.py
  tests/test_benchviewer.py
  tests/test_pregenerated_zip.py
Labels: enhancement, continuous integration
