Repository munich-quantum-toolkit/bench, pull requests merged in 2025-05, with the labels that each got.

#548 :art: Refactored Implementation of Shor's Benchmark
  src/mqt/bench/benchmarks/shor.py
  tests/test_bench.py
Labels: python, refactor

#549 :art: Removed `Provider` and improved `Device` Structure
  docs/Benchmark_selection.rst
  docs/Parameter.rst
  docs/Quickstart.ipynb
  docs/conf.py
  pyproject.toml
  src/mqt/bench/benchmark_generation.py
  src/mqt/bench/calibration_files/ibm_montreal_calibration.json
  src/mqt/bench/calibration_files/ibm_washington_calibration.json
  src/mqt/bench/cli.py
  src/mqt/bench/devices/__init__.py
  src/mqt/bench/devices/calibration.py
  src/mqt/bench/devices/device.py
  src/mqt/bench/devices/ibm.py
  src/mqt/bench/devices/ionq.py
  src/mqt/bench/devices/iqm.py
  src/mqt/bench/devices/oqc.py
  src/mqt/bench/devices/provider.py
  src/mqt/bench/devices/quantinuum.py
  src/mqt/bench/devices/rigetti.py
  src/mqt/bench/output.py
  tests/devices/test_devices.py
  tests/devices/test_ibm_device_support.py
  tests/devices/test_ionq_device_support.py
  tests/devices/test_iqm_device_support.py
  tests/devices/test_oqc_device_support.py
  tests/devices/test_quantinuum_device_support.py
  tests/devices/test_rigetti_device_support.py
  tests/test_bench.py
  tests/test_cli.py
  uv.lock
Labels: enhancement, python, refactor

#555 :sparkles: Added `clifford+t` gateset
  pyproject.toml
  src/mqt/bench/benchmark_generation.py
  src/mqt/bench/devices/__init__.py
  tests/test_bench.py
Labels: feature

#556 🔥 server deployment for versions <2
  .github/workflows/cd.yml
Labels: continuous integration

#567 :memo: Added CHANGELOG and UPGRADING information
  .github/contributing.md
  .github/release-drafter.yml
  CHANGELOG.md
  UPGRADING.md
  docs/CHANGELOG.md
  docs/UPGRADING.md
  docs/index.md
Labels: documentation

#566 :memo: Update Documentation
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/contributing.md
  .github/support.md
  docs/conf.py
  docs/development_guide.md
  docs/index.md
  docs/installation.md
Labels: documentation

#569 🚨Fixed Pending Deprecation Warnings
  docs/benchmark_selection.md
  pyproject.toml
  src/mqt/bench/benchmark_generation.py
  src/mqt/bench/benchmarks/ae.py
  src/mqt/bench/benchmarks/graphstate.py
  src/mqt/bench/benchmarks/grover.py
  src/mqt/bench/benchmarks/qft.py
  src/mqt/bench/benchmarks/qftentangled.py
  src/mqt/bench/benchmarks/qnn.py
  src/mqt/bench/benchmarks/qpeexact.py
  src/mqt/bench/benchmarks/qpeinexact.py
  src/mqt/bench/benchmarks/qwalk.py
  src/mqt/bench/benchmarks/shor.py
  src/mqt/bench/benchmarks/vqerealamprandom.py
  src/mqt/bench/benchmarks/vqesu2random.py
  src/mqt/bench/benchmarks/vqetwolocalrandom.py
  src/mqt/bench/cli.py
  tests/test_bench.py
  uv.lock
Labels: refactor

#573 💡 updated readme and RtDs according to new guidelines
  README.md
  docs/_templates/page.html
  docs/conf.py
  docs/index.md
Labels: documentation, enhancement

#584 💡 fixed broken reference in readme
  README.md
Labels: documentation

#581 ✨ add option to parameterized benchmarks to create circuits with symbolic parameters
  src/mqt/bench/benchmark_generation.py
  src/mqt/bench/benchmarks/bmw_quark_cardinality.py
  src/mqt/bench/benchmarks/bmw_quark_copula.py
  src/mqt/bench/benchmarks/qaoa.py
  src/mqt/bench/benchmarks/qnn.py
  src/mqt/bench/benchmarks/vqe_real_amp.py
  src/mqt/bench/benchmarks/vqe_su2.py
  src/mqt/bench/benchmarks/vqe_two_local.py
  src/mqt/bench/benchmarks/vqetwolocalrandom.py
  tests/test_bench.py
Labels: feature

#587 :art: Simplify Imports
  src/mqt/bench/benchmarks/ae.py
  src/mqt/bench/benchmarks/graphstate.py
  src/mqt/bench/benchmarks/grover.py
  src/mqt/bench/benchmarks/hhl.py
  src/mqt/bench/benchmarks/qnn.py
  src/mqt/bench/benchmarks/vqe_real_amp.py
  src/mqt/bench/benchmarks/vqe_su2.py
  src/mqt/bench/benchmarks/vqe_two_local.py
Labels: refactor
