Repository munich-quantum-toolkit/bench, pull requests merged in 2025-06, with the labels that each got.

#585 :sparkles: Benchmark Registry
  docs/development_guide.md
  docs/parameter.md
  src/mqt/bench/benchmark_generation.py
  src/mqt/bench/benchmarks/__init__.py
  src/mqt/bench/benchmarks/_registry.py
  src/mqt/bench/benchmarks/ae.py
  src/mqt/bench/benchmarks/bmw_quark_cardinality.py
  src/mqt/bench/benchmarks/bmw_quark_copula.py
  src/mqt/bench/benchmarks/bv.py
  src/mqt/bench/benchmarks/dj.py
  src/mqt/bench/benchmarks/ghz.py
  src/mqt/bench/benchmarks/graphstate.py
  src/mqt/bench/benchmarks/grover.py
  src/mqt/bench/benchmarks/hhl.py
  src/mqt/bench/benchmarks/qaoa.py
  src/mqt/bench/benchmarks/qft.py
  src/mqt/bench/benchmarks/qftentangled.py
  src/mqt/bench/benchmarks/qnn.py
  src/mqt/bench/benchmarks/qpeexact.py
  src/mqt/bench/benchmarks/qpeinexact.py
  src/mqt/bench/benchmarks/qwalk.py
  src/mqt/bench/benchmarks/randomcircuit.py
  src/mqt/bench/benchmarks/shor.py
  src/mqt/bench/benchmarks/vqe_real_amp.py
  src/mqt/bench/benchmarks/vqe_su2.py
  src/mqt/bench/benchmarks/vqe_two_local.py
  src/mqt/bench/benchmarks/wstate.py
  src/mqt/bench/targets/__init__.py
  src/mqt/bench/targets/devices/__init__.py
  src/mqt/bench/targets/devices/_registry.py
  src/mqt/bench/targets/devices/ibm.py
  src/mqt/bench/targets/devices/ionq.py
  src/mqt/bench/targets/devices/iqm.py
  src/mqt/bench/targets/devices/quantinuum.py
  src/mqt/bench/targets/devices/rigetti.py
  src/mqt/bench/targets/gatesets/__init__.py
  src/mqt/bench/targets/gatesets/_registry.py
  src/mqt/bench/targets/gatesets/clifford_t.py
  src/mqt/bench/targets/gatesets/ibm.py
  src/mqt/bench/targets/gatesets/ionq.py
  src/mqt/bench/targets/gatesets/iqm.py
  src/mqt/bench/targets/gatesets/quantinuum.py
  src/mqt/bench/targets/gatesets/rigetti.py
  tests/test_bench.py
  tests/test_targets.py
Labels: enhancement, refactor

#577 ✨ feat: implement mirror circuit generation for device benchmarking
  src/mqt/bench/benchmark_generation.py
  src/mqt/bench/cli.py
  src/mqt/bench/output.py
  tests/test_bench.py
  tests/test_cli.py
Labels: feature

#602 ⚡ Speed up test suite
  noxfile.py
  pyproject.toml
  sitecustomize.py
  src/mqt/bench/targets/devices/ibm.py
  uv.lock
Labels: continuous integration, usability

#603 🐛 Fix mirror circuit generation on mapped level
  src/mqt/bench/benchmark_generation.py
  tests/test_bench.py
Labels: fix

#601 :sparkles: Add random parameter option to cli
  src/mqt/bench/cli.py
  tests/test_cli.py
Labels: enhancement

#597 :memo: Prepared Documentation for the 2.0 Realease
  README.md
  docs/benchmark_selection.md
  docs/development_guide.md
  docs/installation.md
  docs/parameter.md
  docs/quickstart.md
  pyproject.toml
  src/mqt/bench/benchmarks/__init__.py
  src/mqt/bench/benchmarks/_registry.py
  src/mqt/bench/benchmarks/ae.py
  src/mqt/bench/benchmarks/bmw_quark_cardinality.py
  src/mqt/bench/benchmarks/bmw_quark_copula.py
  src/mqt/bench/benchmarks/bv.py
  src/mqt/bench/benchmarks/cdkm_ripple_carry_adder.py
  src/mqt/bench/benchmarks/dj.py
  src/mqt/bench/benchmarks/draper_qft_adder.py
  src/mqt/bench/benchmarks/full_adder.py
  src/mqt/bench/benchmarks/ghz.py
  src/mqt/bench/benchmarks/graphstate.py
  src/mqt/bench/benchmarks/grover.py
  src/mqt/bench/benchmarks/half_adder.py
  src/mqt/bench/benchmarks/hhl.py
  src/mqt/bench/benchmarks/hrs_cumulative_multiplier.py
  src/mqt/bench/benchmarks/modular_adder.py
  src/mqt/bench/benchmarks/multiplier.py
  src/mqt/bench/benchmarks/qaoa.py
  src/mqt/bench/benchmarks/qft.py
  src/mqt/bench/benchmarks/qftentangled.py
  src/mqt/bench/benchmarks/qnn.py
  src/mqt/bench/benchmarks/qpeexact.py
  src/mqt/bench/benchmarks/qpeinexact.py
  src/mqt/bench/benchmarks/qwalk.py
  src/mqt/bench/benchmarks/randomcircuit.py
  src/mqt/bench/benchmarks/rg_qft_multiplier.py
  src/mqt/bench/benchmarks/shor.py
  src/mqt/bench/benchmarks/vbe_ripple_carry_adder.py
  src/mqt/bench/benchmarks/vqe_real_amp.py
  src/mqt/bench/benchmarks/vqe_su2.py
  src/mqt/bench/benchmarks/vqe_two_local.py
  src/mqt/bench/benchmarks/wstate.py
  tests/test_bench.py
  uv.lock
Labels: documentation

#608 💡 adjusted date of release to today
  CHANGELOG.md
Labels: documentation
