Repository munich-quantum-toolkit/bench, pull requests merged in 2025-04, with the labels that each got.

#506 🎨 Re-implemented AE without Qiskit Application Modules
  src/mqt/bench/benchmarks/ae.py
  tests/test_bench.py
Labels: python, refactor

#507 🔥 Removed all Benchmarks relying on `qiskit_optimization`, `qiskit_nature`, and `qiskit_algorithm` Dependencies
  .pre-commit-config.yaml
  pyproject.toml
  src/mqt/bench/benchmark_generator.py
  src/mqt/bench/benchmarks/__init__.py
  src/mqt/bench/benchmarks/grover.py
  src/mqt/bench/benchmarks/qaoa.py
  src/mqt/bench/benchmarks/qiskit_application_finance/portfolioqaoa.py
  src/mqt/bench/benchmarks/qiskit_application_finance/portfoliovqe.py
  src/mqt/bench/benchmarks/qiskit_application_finance/pricingcall.py
  src/mqt/bench/benchmarks/qiskit_application_finance/pricingput.py
  src/mqt/bench/benchmarks/qiskit_application_nature/groundstate.py
  src/mqt/bench/benchmarks/qiskit_application_optimization/routing.py
  src/mqt/bench/benchmarks/qiskit_application_optimization/tsp.py
  src/mqt/bench/benchmarks/shor.py
  src/mqt/bench/benchmarks/vqe.py
  src/mqt/bench/cli.py
  src/mqt/bench/config.json
  src/mqt/bench/utils.py
  tests/test_bench.py
Labels: python, refactor

#508 🚚 Renamed Random Circuit and VQE Ansatz Circuit Benchmarks
  src/mqt/bench/benchmarks/randomcircuit.py
  src/mqt/bench/benchmarks/vqerealamprandom.py
  src/mqt/bench/benchmarks/vqesu2random.py
  src/mqt/bench/benchmarks/vqetwolocalrandom.py
  src/mqt/bench/config.json
  src/mqt/bench/utils.py
  tests/test_bench.py
Labels: python, usability, refactor

#510 🔥 Removed Placement Parameter for TKET Mapped Benchmarks
  docs/Quickstart.ipynb
  src/mqt/bench/__init__.py
  src/mqt/bench/benchmark_generator.py
  src/mqt/bench/cli.py
  src/mqt/bench/tket_helper.py
  tests/test_bench.py
Labels: python, refactor

#509 🎨 Miscellaneous Fixes
  pyproject.toml
  src/mqt/bench/benchmarks/__init__.py
  src/mqt/bench/benchmarks/qnn.py
  src/mqt/bench/tket_helper.py
  src/mqt/bench/utils.py
  tests/test_bench.py
  uv.lock
Labels: dependencies, python, refactor

#518 ✨ Added QASM3 support
  pyproject.toml
  src/mqt/bench/benchmark_generator.py
  src/mqt/bench/benchmarks/ae.py
  src/mqt/bench/benchmarks/graphstate.py
  src/mqt/bench/qiskit_helper.py
  src/mqt/bench/tket_helper.py
  src/mqt/bench/utils.py
  tests/test_bench.py
  uv.lock
Labels: enhancement, python

#531 :sparkles: Re-add support for Python 3.9
  noxfile.py
  pyproject.toml
  src/mqt/bench/benchmark_generation.py
  uv.lock
Labels: dependencies, feature

#530 ✨ Introduce `Hatchling` and `dependency-groups`
  .github/renovate.json5
  .pre-commit-config.yaml
  .readthedocs.yaml
  noxfile.py
  pyproject.toml
  uv.lock
Labels: dependencies, python, packaging, refactor

#543 📝 Update README and resource links due to repository migration
  README.md
  docs/_templates/page.html
Labels: documentation

#540 ♻️ refactored output module
  src/mqt/bench/benchmark_generation.py
  src/mqt/bench/benchmarks/randomcircuit.py
  src/mqt/bench/cli.py
  src/mqt/bench/output.py
  src/mqt/bench/utils.py
  tests/test_bench.py
  tests/test_cli.py
Labels: python, refactor

#544 ✨ Move to MQT GitHub Orga and Re-Branding
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/contributing.rst
  .github/support.rst
  .license-tools-config.json
  .pre-commit-config.yaml
  LICENSE.md
  README.md
  docs/DevelopmentGuide.rst
  docs/Usage.rst
  docs/conf.py
  docs/index.rst
  noxfile.py
  pyproject.toml
  src/mqt/bench/__init__.py
  src/mqt/bench/benchmark_generation.py
  src/mqt/bench/benchmarks/__init__.py
  src/mqt/bench/benchmarks/ae.py
  src/mqt/bench/benchmarks/bv.py
  src/mqt/bench/benchmarks/dj.py
  src/mqt/bench/benchmarks/ghz.py
  src/mqt/bench/benchmarks/graphstate.py
  src/mqt/bench/benchmarks/grover.py
  src/mqt/bench/benchmarks/qaoa.py
  src/mqt/bench/benchmarks/qft.py
  src/mqt/bench/benchmarks/qftentangled.py
  src/mqt/bench/benchmarks/qnn.py
  src/mqt/bench/benchmarks/qpeexact.py
  src/mqt/bench/benchmarks/qpeinexact.py
  src/mqt/bench/benchmarks/qwalk.py
  src/mqt/bench/benchmarks/randomcircuit.py
  src/mqt/bench/benchmarks/shor.py
  src/mqt/bench/benchmarks/vqerealamprandom.py
  src/mqt/bench/benchmarks/vqesu2random.py
  src/mqt/bench/benchmarks/vqetwolocalrandom.py
  src/mqt/bench/benchmarks/wstate.py
  src/mqt/bench/cli.py
  src/mqt/bench/devices/__init__.py
  src/mqt/bench/devices/calibration.py
  src/mqt/bench/devices/device.py
  src/mqt/bench/devices/ibm.py
  src/mqt/bench/devices/ionq.py
  src/mqt/bench/devices/iqm.py
  src/mqt/bench/devices/oqc.py
  src/mqt/bench/devices/provider.py
  src/mqt/bench/devices/quantinuum.py
  src/mqt/bench/devices/rigetti.py
  src/mqt/bench/output.py
  tests/devices/test_devices.py
  tests/devices/test_ibm_device_support.py
  tests/devices/test_ionq_device_support.py
  tests/devices/test_iqm_device_support.py
  tests/devices/test_oqc_device_support.py
  tests/devices/test_quantinuum_device_support.py
  tests/devices/test_rigetti_device_support.py
  tests/test_bench.py
  tests/test_cli.py
Labels: documentation

#541 ✨ added two further benchmarks from BMW's QUARK
  src/mqt/bench/benchmarks/quarkcardinality.py
  src/mqt/bench/benchmarks/quarkcopula.py
  tests/test_bench.py
Labels: feature
